### ISSUE TITLE
Request to place the required files in zip and put in release section.

### ISSUE THREAD

**Issue by TontyTon** [GChuf/RCWM#1]
Can you to place the required files in zip and put in release section. For less that 1 MB files, we have to download around 50MB.

**Comment by GChuf** [comment]
Thanks for the report/idea! I've just noticed now that the gif files were present in both _img_ and _files_ folders. Nonetheless, these gifs shouldn't ever be downloaded.

I'll make a zip file later today hopefully, after I make some changes to "Take Ownership".

**Comment by GChuf** [comment]
@TontyTon First release is now up!
https://github.com/GChuf/RCWM/releases

**Comment by TontyTon** [comment]
Thanks a lot.
