### ISSUE TITLE
How to undo the changes made by the install.bat file?

### ISSUE THREAD

**Issue by TontyTon** [GChuf/RCWM#2]
I added multiple context menu items, now I want to remove some, can you make another bat file to remove the RoboCopy from context menu and re-add old context menu items.

**Comment by GChuf** [comment]
I wanted to create an uninstall .bat script, but I think it's better to just create individual .reg files to remove RCWM menu items.

Re-adding old context menu items might not always work (depends on the user's windows version), but I'll make those reg files as well.

**Comment by GChuf** [comment]
@TontyTon take a look inside the "uninstall" folder - I tested the .reg files and they seem to work for me. Let me know if re-adding the original context-menu items won't work for you.

**Comment by GChuf** [comment]
P.S. consider starring ⭐ the repository - it would help in these early stages :)

**Comment by TontyTon** [comment]
Ya, I tested the uninstall files, they are working, including the adding of original context menu items.
