### ISSUE TITLE
Option to limit copying speed in RoboCopy

### ISSUE THREAD

**Issue by shelltar** [GChuf/RCWM#23]
Hi there, I am a user of RCWM and I appreciate your work on this tool. I have a suggestion for a new feature that would make it more useful for me and maybe others.

I use rsync to mount Google Drive as a network disk, and I often use RCWM to copy files to and from it. However, I have a problem with the network bandwidth usage. RoboCopy always uses 100% of my network speed, which makes my internet connection very slow for other tasks. This is not convenient for me, especially when I need to copy large files or folders.

I would like to have an option to limit the copying speed in RoboCopy, so that I can balance the network usage between copying and other activities. I know that RoboCopy has a parameter called /IPG that can do this. For example, if I want to limit the bandwidth usage to 1 Mbps (1000 Kbps), I can use /IPG:100.

It would be great if you could add a feature to RCWM that allows me to set the /IPG parameter for RoboCopy in the context menu. This way, I can easily choose the copying speed that suits my needs.

Thank you for your time and attention. I hope you will consider this feature request and let me know what you think.

**Comment by shelltar** [comment]
Never mind, I added --bwlimit to the rclone service, and it works just fine.

**Comment by GChuf** [comment]
@V3semir thanks for opening this. I was thinking about adding the option to add/change robocopy flags to the user, but I gotta figure out how to do it. It's definitely on the to-do list.
If you got any other suggestions or comments, let me know!
