### ISSUE TITLE
DLL's

### ISSUE THREAD

**Issue by simonmcnair** [GChuf/RCWM#25]
I like that I can see the ps1 files, and the batch files etc.  What I can't see is the source for the icon dll that is very often ran, or that the dll was created with the source provided.

From a security perspective that makes me much more cautious that the reg files, cmd files or ps1 files.

Just my opinion.
Cheers
Simon

**Comment by GChuf** [comment]
Hi,
the dll files get compiled on your syatem after you run the installer. The script InitialSetup.ps1 can be found under the "InstallerFiles" folder. It takes the icon files from the "ps2exe" subfolder, which are copied to a temporary folder during the install. 
An example from the script is copied below. I use my own version of the ps2exe script. Notice the iconfile parameter.
`powershell .\Temp\ps2exe_bastardized.ps1 -inputfile .\Temp\RCopySingle.ps1 -outputfile .\Temp\rcopyS.exe -noconsole -novisualstyles -x86 -nooutput -iconfile .\Temp\rcopy.ico 2>&1>$null`
