### ISSUE TITLE
RoboCopy/RoboPaste Directory Structure

### ISSUE THREAD

**Issue by paradoxicallist** [GChuf/RCWM#8]
Hello

As the title says, no files just folders and subfolders, please.

**Comment by GChuf** [comment]
Hi,

I'm not sure this is possible with robocopy - do you have a robocopy command that can do this?

**Comment by paradoxicallist** [comment]
I got these parameters for robocopy, for example.
`/xf *`
`/e`

**Comment by GChuf** [comment]
/XF works perfectly, I've added the option in release v1.5.4.
https://github.com/GChuf/RCWM/releases/tag/v1.5.4

**Comment by paradoxicallist** [comment]
Testing v1.5.4 on Windows 7 x86 on a 64-bit CPU on a very low specs old laptop.

The only option I install is:
RoboCopy to copy Folder Structure only (exclude files)

When I RoboPaste Structure a cmdline window pops up showing this message:
`The system cannot write to the specified device.
Exiting...`

**Comment by GChuf** [comment]
@MrX-at-GitHub this was linked to the fact that encoding on Windows 7 is different than on Win8/10/11 - I fixed it and it should work for you now.
(It's possible that some special characters won't work when copying/pasting on windows7 - I still have to include that warning somewhere.)
Re-download the v1.5.4 release, reinstall, and you are good to go.

**Comment by paradoxicallist** [comment]
Thank you.  v1.5.4 is working now but only if I RoboPaste to another different directory. If I want to RoboPaste into the same parent directory ie aside the folder I want to copy, RoboCopy offers to overwrite or merge:
`Folder with the same name already exists: TestFolder
Merge/Overwrite/Cancel? [M,O,C]?`

Is there a solution to this?
I mean, make RoboCopy able to append a number or anything to the original foldername?
`TestFolder (1)`
Just like normal copy function does under Windows, please.

One more little request, just a cosmetic little detail to make context menu more understandable:
`RoboCopy Structure`  to `RoboCopy Folder Structure `
and
`RoboPaste Structure` to `RoboPaste Folder Structure`

**Comment by GChuf** [comment]
RoboCopy itself isn't capable of doing that I think, so it would have to be solved on the script level.
I might add it in at some point, but it requires some work and some testing.

As for the text, I tried to make it as small as possible, but I think I can add "Folder" in there as well.

**Comment by paradoxicallist** [comment]
Well I notice that too, that RoboCopy itself run from a cmd line windows is not capable of copying in the same directory but someone at another forum passed me this reg tweak and it worked out, just by importing it to the registry RoboCopy copies the folder structure in the same directory. Take a look please as it might help somehow:


Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\RoboCopyFolderStructure]
@="RoboCopy Folder Structure"
"Icon"="imageres.dll,153"

[HKEY_CLASSES_ROOT\Directory\shell\RoboCopyFolderStructure\command]
@="robocopy.exe \"%1\" \"%1 - RoboCopy\"\\ /xf * /e"

**Comment by GChuf** [comment]
@MrX-at-GitHub I see what the example is doing, it just appends "- RoboCopy" to the end of the folder name. I wouldn't like to include this in the code - but as long as it helps you you should use it, of course.
